#region AgileEAS.NET-generated
//------------------------------------------------------------------------------
//     AgileEAS.NET应用开发平台，是基于敏捷并行开发思想以及.NET构件技术而开发的一个应用系统快速开发平台，用于帮助中小软件企业
//建立一条适合快速变化的开发团队，以达到节省开发成本、缩短开发时间，快速适应市场变化的目的。
//     AgileEAS.NET应用开发平台包含基础类库、资源管理平台、运行容器、开发辅助工具等四大部分，资源管理平台为敏捷并行开发提供了
//设计、实现、测试等开发过程的并行，应用系统的各个业务功能子系统，在系统体系结构设计的过程中被设计成各个原子功能模块，各个子
//功能模块按照业务功能组织成单独的程序集文件，各子系统开发完成后，由AgileEAS.NET资源管理平台进行统一的集成部署。
//
//     AgileEAS.NET SOA 中间件平台是一套免费的快速开发工具，可以不受限制的用于各种非商业开发之中，商业应用请向作者获取商业授权，
//商业授权也是免费的，但是对于非授权的商业应用视为侵权，开发人员可以参考官方网站和博客园等专业网站获取公开的技术资料，也可以向
//AgileEAS.NET官方团队请求技术支持。
//
// 官方网站：http://www.smarteas.net
// 团队网站：http://www.agilelab.cn
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由AgileEAS.NET数据模型设计工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Data;
using EAS.Data;
using EAS.Data.Access;
using EAS.Data.ORM;
using EAS.Data.Linq;

namespace AgileHIS.Entities
{
    /// <summary>
    /// 实体对象 HFareDetail(住院费用明细记录)。
    /// </summary>
    [Serializable()]
    [DataContract(IsReference = true)]
    [Table("HM_FAREDETAIL", "住院费用明细记录")]
    partial class HFareDetail : DataEntity<HFareDetail>, IDataEntity<HFareDetail>
    {
        public HFareDetail()
        {
        }

        protected HFareDetail(SerializationInfo info, StreamingContext context)
            : base(info, context)
        {
        }

        #region O/R映射成员

        /// <summary>
        /// ID 。
        /// </summary>
        [Column("ID", "ID"), PrimaryKey, NotNull]
        [DisplayName("ID")]
        [DataMember]
        public int ID
        {
            get;
            set;
        }

        /// <summary>
        /// 病人编号 。
        /// </summary>
        [Column("Patient", "病人编号")]
        [DisplayName("病人编号")]
        [DataMember]
        public int Patient
        {
            get;
            set;
        }

        /// <summary>
        /// 住院流水号 。
        /// </summary>
        [Column("Pnumber", "住院流水号")]
        [DisplayName("住院流水号")]
        [DataMember]
        public int PNumber
        {
            get;
            set;
        }

        /// <summary>
        /// 住院次数 。
        /// </summary>
        [Column("Times", "住院次数")]
        [DisplayName("住院次数")]
        [DataMember]
        public short Times
        {
            get;
            set;
        }

        /// <summary>
        /// 姓名 。
        /// </summary>
        [Column("NAME", "姓名"), DataSize(128)]
        [DisplayName("姓名")]
        [DataMember]
        public string Name
        {
            get;
            set;
        }

        /// <summary>
        /// 医嘱号码 。
        /// </summary>
        [Column("AdviceCode", "医嘱号码")]
        [DisplayName("医嘱号码")]
        [DataMember]
        public long AdviceCode
        {
            get;
            set;
        }

        /// <summary>
        /// 项目编号 。
        /// </summary>
        [Column("ItemCode", "项目编号")]
        [DisplayName("项目编号")]
        [DataMember]
        public int ItemCode
        {
            get;
            set;
        }

        /// <summary>
        /// 药品ID 。
        /// </summary>
        [Column("ItemID", "药品ID")]
        [DisplayName("药品ID")]
        [DataMember]
        public long ItemID
        {
            get;
            set;
        }

        /// <summary>
        /// 项目名称 。
        /// </summary>
        [Column("ItemName", "项目名称"), DataSize(128)]
        [DisplayName("项目名称")]
        [DataMember]
        public string ItemName
        {
            get;
            set;
        }

        /// <summary>
        /// 规格 。
        /// </summary>
        [Column("Spec", "规格"), DataSize(128)]
        [DisplayName("规格")]
        [DataMember]
        public string Spec
        {
            get;
            set;
        }

        /// <summary>
        /// 大单位 。
        /// </summary>
        [Column("BigUnit", "大单位"), DataSize(128)]
        [DisplayName("大单位")]
        [DataMember]
        public string BigUnit
        {
            get;
            set;
        }

        /// <summary>
        /// 小单位 。
        /// </summary>
        [Column("SmallUnit", "小单位"), DataSize(128)]
        [DisplayName("小单位")]
        [DataMember]
        public string SmallUnit
        {
            get;
            set;
        }

        /// <summary>
        /// 分装规则 。
        /// </summary>
        [Column("PackRule", "分装规则")]
        [DisplayName("分装规则")]
        [DataMember]
        public int PackRule
        {
            get;
            set;
        }

        /// <summary>
        /// 包装类型 。
        /// </summary>
        [Column("PackType", "包装类型")]
        [DisplayName("包装类型")]
        [DataMember]
        public int PackType
        {
            get;
            set;
        }

        /// <summary>
        /// 支付类型 。
        /// </summary>
        [Column("InsureType", "支付类型")]
        [DisplayName("支付类型")]
        [DataMember]
        public int InsureType
        {
            get;
            set;
        }

        /// <summary>
        /// 药品效期 。
        /// </summary>
        [Column("TimeLimit", "药品效期")]
        [DisplayName("药品效期")]
        [DataMember]
        public DateTime TimeLimit
        {
            get;
            set;
        }

        /// <summary>
        /// 药品属性 。
        /// </summary>
        [Column("Attribute", "药品属性")]
        [DisplayName("药品属性")]
        [DataMember]
        public int Attribute
        {
            get;
            set;
        }

        /// <summary>
        /// OTC类型 。
        /// </summary>
        [Column("OTCTYPE", "OTC类型")]
        [DisplayName("OTC类型")]
        [DataMember]
        public int OtcType
        {
            get;
            set;
        }

        /// <summary>
        /// 药理类型 。
        /// </summary>
        [Column("Action", "药理类型")]
        [DisplayName("药理类型")]
        [DataMember]
        public int Action
        {
            get;
            set;
        }

        /// <summary>
        /// 药品类型 。
        /// </summary>
        [Column("Type", "药品类型")]
        [DisplayName("药品类型")]
        [DataMember]
        public int Type
        {
            get;
            set;
        }

        /// <summary>
        /// 药品剂型 。
        /// </summary>
        [Column("AgentType", "药品剂型")]
        [DisplayName("药品剂型")]
        [DataMember]
        public int AgentType
        {
            get;
            set;
        }

        /// <summary>
        /// 单价 。
        /// </summary>
        [Column("Price", "单价"), DataSize(18, 4)]
        [DisplayName("单价")]
        [DataMember]
        public decimal Price
        {
            get;
            set;
        }

        /// <summary>
        /// 剂量 。
        /// </summary>
        [Column("Dosage", "剂量"), DataSize(18)]
        [DisplayName("剂量")]
        [DataMember]
        public decimal Dosage
        {
            get;
            set;
        }

        /// <summary>
        /// 剂量 。
        /// </summary>
        [Column("DosageUnit", "剂量"), DataSize(16)]
        [DisplayName("剂量")]
        [DataMember]
        public string DosageUnit
        {
            get;
            set;
        }

        /// <summary>
        /// 数量 。
        /// </summary>
        [Column("XNUMBER", "数量")]
        [DisplayName("数量")]
        [DataMember]
        public int Number
        {
            get;
            set;
        }

        /// <summary>
        /// 金额 。
        /// </summary>
        [Column("Cash", "金额"), DataSize(18, 4)]
        [DisplayName("金额")]
        [DataMember]
        public decimal Cash
        {
            get;
            set;
        }

        /// <summary>
        /// 住院发票分类 。
        /// </summary>
        [Column("KINDCODE2", "住院发票分类")]
        [DisplayName("住院发票分类")]
        [DataMember]
        public short KindCode2
        {
            get;
            set;
        }

        /// <summary>
        /// 内部核算分类 。
        /// </summary>
        [Column("KINDCODE3", "内部核算分类")]
        [DisplayName("内部核算分类")]
        [DataMember]
        public short KindCode3
        {
            get;
            set;
        }

        /// <summary>
        /// 病案首页分类 。
        /// </summary>
        [Column("KINDCODE4", "病案首页分类")]
        [DisplayName("病案首页分类")]
        [DataMember]
        public short KindCode4
        {
            get;
            set;
        }

        /// <summary>
        /// 会计科目分类 。
        /// </summary>
        [Column("KINDCODE5", "会计科目分类")]
        [DisplayName("会计科目分类")]
        [DataMember]
        public short KindCode5
        {
            get;
            set;
        }

        /// <summary>
        /// 分类标志0费用1药品2材料 。
        /// </summary>
        [Column("CATEGORY", "分类标志0费用1药品2材料")]
        [DisplayName("分类标志0费用1药品2材料")]
        [DataMember]
        public byte Category
        {
            get;
            set;
        }

        /// <summary>
        /// 用药方式 。
        /// </summary>
        [Column("Method", "用药方式")]
        [DisplayName("用药方式")]
        [DataMember]
        public int Method
        {
            get;
            set;
        }

        /// <summary>
        /// 频率 。
        /// </summary>
        [Column("Frequence", "频率")]
        [DisplayName("频率")]
        [DataMember]
        public int Frequence
        {
            get;
            set;
        }

        /// <summary>
        /// 开立时间 。
        /// </summary>
        [Column("CreateTime", "开立时间")]
        [DisplayName("开立时间")]
        [DataMember]
        public DateTime CreateTime
        {
            get;
            set;
        }

        /// <summary>
        /// 开立者 。
        /// </summary>
        [Column("Creator", "开立者")]
        [DisplayName("开立者")]
        [DataMember]
        public int Creator
        {
            get;
            set;
        }

        /// <summary>
        /// 开立科室 。
        /// </summary>
        [Column("DeptID", "开立科室")]
        [DisplayName("开立科室")]
        [DataMember]
        public int DeptID
        {
            get;
            set;
        }

        /// <summary>
        /// 收费时间 。
        /// </summary>
        [Column("CHANGETIME", "收费时间")]
        [DisplayName("收费时间")]
        [DataMember]
        public DateTime ChargeTime
        {
            get;
            set;
        }

        /// <summary>
        /// 收费者 。
        /// </summary>
        [Column("CHANGOR", "收费者")]
        [DisplayName("收费者")]
        [DataMember]
        public int Chargor
        {
            get;
            set;
        }

        /// <summary>
        /// 发药时间 。
        /// </summary>
        [Column("DispenseTime", "发药时间")]
        [DisplayName("发药时间")]
        [DataMember]
        public DateTime DispenseTime
        {
            get;
            set;
        }

        /// <summary>
        /// 发药人 。
        /// </summary>
        [Column("Dispenser", "发药人")]
        [DisplayName("发药人")]
        [DataMember]
        public int Dispenser
        {
            get;
            set;
        }

        /// <summary>
        /// 药房ID 。
        /// </summary>
        [Column("StoreID", "药房ID")]
        [DisplayName("药房ID")]
        [DataMember]
        public int StoreID
        {
            get;
            set;
        }

        /// <summary>
        /// 执行时间 。
        /// </summary>
        [Column("ExecTime", "执行时间")]
        [DisplayName("执行时间")]
        [DataMember]
        public DateTime ExecTime
        {
            get;
            set;
        }

        /// <summary>
        /// 执行科室 。
        /// </summary>
        [Column("EDEPTID", "执行科室")]
        [DisplayName("执行科室")]
        [DataMember]
        public int EDeptID
        {
            get;
            set;
        }

        /// <summary>
        /// 执行者 。
        /// </summary>
        [Column("Executer", "执行者")]
        [DisplayName("执行者")]
        [DataMember]
        public int Executer
        {
            get;
            set;
        }

        /// <summary>
        /// 退费状态0收费1退费 。
        /// </summary>
        [Column("CHANGESTATE", "退费状态0收费1退费")]
        [DisplayName("退费状态0收费1退费")]
        [DataMember]
        public byte ChargeState
        {
            get;
            set;
        }

        /// <summary>
        /// 退药or退费原因 。
        /// </summary>
        [Column("CAUSE", "退药or退费原因"), DataSize(128)]
        [DisplayName("退药or退费原因")]
        [DataMember]
        public string Cause
        {
            get;
            set;
        }

        /// <summary>
        /// SOURCEID 。
        /// </summary>
        [Column("SOURCEID", "SOURCEID")]
        [DisplayName("SOURCEID")]
        [DataMember]
        public int SourceID
        {
            get;
            set;
        }

        /// <summary>
        /// TransID 。
        /// </summary>
        [Column("TRANSID", "医嘱执行ID"), NotNull]
        [DisplayName("医嘱执行ID")]
        [DataMember]
        public int TransID
        {
            get;
            set;
        }

        #endregion

        #region O/R子实体

        #endregion
    }
}
